name: for_later_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  receive_sharing_intent: ^1.8.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  go_router: ^8.2.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  equatable: ^2.0.5
  injectable: ^2.3.2
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.6
  url_launcher: ^6.3.0
  metadata_fetch: ^0.4.1

  # Firebase
  # firebase_core: ^3.2.0
  # firebase_auth: ^5.1.2
  # google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Lota
      fonts:
        - asset: assets/fonts/lota-thin.otf
          weight: 300
        - asset: assets/fonts/lota-light.otf
          weight: 400
        - asset: assets/fonts/lota-regular.otf
          weight: 500
        - asset: assets/fonts/lota-semi-bold.otf
          weight: 600
        - asset: assets/fonts/lota-bold.otf
          weight: 700
        - asset: assets/fonts/lota-black.otf
          weight: 800